### ISSUE TITLE
Is there Symfony bundle for Scrapbook?

### ISSUE THREAD

**Issue by sunra** [matthiasmullie/scrapbook#8]
in code? in plans?

**Comment by matthiasmullie** [comment]
Hey @sunra. There is none at the moment, and I didn't have any plans to create one (yet).

You wouldn't happen to be interested in building one? I'd be happy to help out!

**Comment by rlataguerra** [comment]
a symfony bundle would be great

**Comment by radoslavius** [comment]
no need imho

yml:

``` yml
parameters:
    cache_sqlite_db: 'sqlite:%kernel.root_dir%/../var/cache/%kernel.environment%/cache.db'

services:
    cache.db:
        class: PDO
        arguments: ["%cache_sqlite_db%"]

    cache.adapter:
        class: MatthiasMullie\Scrapbook\Adapters\SQLite
        arguments: ["@cache.db"]

    cache.pool:
        class: MatthiasMullie\Scrapbook\Psr6\Pool
        arguments: ["@cache.adapter"]

    cache.taggablepool:
        class: MatthiasMullie\Scrapbook\Psr6\Taggable\Pool
        arguments: ["@cache.pool"]
```

usage in controller:

``` php
$pool = $this->get('cache.taggablepool');
$item = $pool->getItem('your_key');
if (!is_null($item->get())) {
    $data = $item->get();
}
else {
    $data = // do something to cache
    $item->set($data);
    $item->expiresAfter(600); //cache for 10 minutes
    $pool->save($item);
}
```
